
name: Docker Build and Push
#Versions
env:
  CURRENT_TAG: <Current-Tag>
  PREV_TAG: <Previous-Tag>

permissions:
  contents: read
  packages: write
  issues: write

  id-token: write
  security-events: write

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
     
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image For Trivy
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/<Dockerhub-Repo-Name>:${{ env.CURRENT_TAG }} .


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/<Dockerhub-Repo-Name>:${{ env.CURRENT_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '2'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'


      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/<Dockerhub-Repo-Name>:${{ env.CURRENT_TAG }}
            

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          
      - name: Clone repository
        run: git clone git@github.com:<username>/Manifests.git


      - name: Update Manifests
        run: |
         sed -i 's/image: <Dockerhub-Username>\/<Dockerhub-Repo-Name>:${{ env.PREV_TAG }}/image: <Dockerhub-Username>\/<Dockerhub-Repo-Name>:${{ env.CURRENT_TAG }}/g' Manifests/deployment.yml

      - name: Commit and push changes
        run: |
          cd Manifests
          git config --global user.email "<username>"
          git config --global user.name "<Name>"
          git add deployment.yml
          git commit -m "Update image version"
          git push origin main

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          allow_issue_writing: true
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ secrets.APP_URL }}
          fail_action: true

      - name: ntfy-success-notifications
        uses: niniyas/ntfy-action@master
        if: success()
        with:
          url: ${{ secrets.ntfy_URL }}
          topic: ${{ secrets.ntfy_TOPIC }}
          headers: ${{ secrets.ntfy_HEADER }}
          tags: +1,partying_face,action,successfully,completed
          details: Workflow has been successfully completed!


      - name: ntfy-failed-notifications
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url:  ${{ secrets.ntfy_URL }}
          topic: ${{ secrets.ntfy_TOPIC }}
          headers: ${{ secrets.ntfy_HEADER }}
          tags: exclamation,x,action,failed
          details: Workflow has failed!
          actions: 'default'

      - name: ntfy-cancelled-notifications
        uses: niniyas/ntfy-action@master
        if: cancelled()
        with:
          url: ${{ secrets.ntfy_URL }}
          topic: ${{ secrets.ntfy_TOPIC }}
          headers: ${{ secrets.ntfy_HEADER }}
          tags: triangular_flag_on_post,x,action,cancelled
          details: Workflow has been cancelled!

            